services:
  train:
    image: nvcr.io/nvidia/tensorflow:23.07-tf2-py3 # or switch to 24.09-tf2-py3 if needed
    runtime: nvidia
    environment:
      - TF_CPP_MIN_LOG_LEVEL=1
    volumes:
      - .:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
    command: >
      bash -c "
        pip install resampy==0.4.3 &&
        pip install python-speech-features==0.6 &&
        python train.py
      "

  run:
    image: nvcr.io/nvidia/tensorflow:23.07-tf2-py3 # or switch to 24.09-tf2-py3 if needed
    runtime: nvidia
    environment:
      - TF_CPP_MIN_LOG_LEVEL=1
      - PYOPENGL_PLATFORM=osmesa
      - MUJOCO_GL=osmesa
    volumes:
      - .:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
    command: >
      bash -c "
        apt update -y &&
        apt install -y libosmesa6 ffmpeg &&
        pip install resampy==0.4.3 &&
        pip install python-speech-features==0.6 &&
        pip install opencv-python==4.10.0.84 &&
        pip install trimesh==4.4.9 &&
        pip install pyrender==0.1.45 &&
        pip install meshio==5.3.5 &&
        pip install pyopengl==3.1.4 &&
        pip install networkx==3.4.1 &&
        python run.py
      "

  dev:
    image: nvcr.io/nvidia/tensorflow:23.07-tf2-py3 # or switch to 24.09-tf2-py3 if needed
    runtime: nvidia
    environment:
      - PYOPENGL_PLATFORM=osmesa
      - MUJOCO_GL=osmesa
    volumes:
      - .:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
    command: >
      bash -c "
        apt update -y &&
        apt install -y libosmesa6 ffmpeg &&
        pip install resampy==0.4.3 &&
        pip install python-speech-features==0.6 &&
        pip install opencv-python==4.10.0.84 &&
        pip install trimesh==4.4.9 &&
        pip install pyrender==0.1.45 &&
        pip install meshio==5.3.5 &&
        pip install pyopengl==3.1.4 &&
        pip install networkx==3.4.1 &&
        pip install chumpy==0.70 &&
        tail -f /dev/null
      "
